openapi: 3.0.0
info:
  title: SpecialBarCode
  description: Magento Module
  version: 1.0.0
paths:
  /sigurd_specialbarcode/product/attribute:
    post:
      summary: Update Product Attribute
      description: This API endpoint allows you to update SpecialBarCode a product attribute using an HTTP POST request.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: integer
                  description: The ID of the product to update the attribute for.
                attributeValue:
                  type: string
                  description: The value of the attribute to be updated.
              required:
                - productId
                - attributeValue
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates if the request was successful.
                  message:
                    type: string
                    description: A message indicating the status of the operation.
                  productId:
                    type: integer
                    description: The ID of the updated product.
        '400':
          description: Bad Request
        '404':
          description: Product Not Found
        '500':
          description: Server Error
